version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: pestova/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/media
  frontend:
    image: pestova/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  nginx:
    image: pestova/foodgram_infra
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/media
      - static:/static
